### ISSUE TITLE
Update check fails

### ISSUE THREAD

**Issue by ortwinbachmann30** [Forkgram/tdesktop#82]
### Steps to reproduce

I don't know

### Expected behaviour

Checking for updates must give one of these two answers

1. No updates available, you're using latest version
2. Downloading update (when an update is available)

### Actual behaviour

It says update check failed.
![Snag_1dfc6bb2](https://user-images.githubusercontent.com/74976078/210077019-756a255b-c48d-487d-8ce2-32310058440f.png)

### Operating system

Windows 11

### Version of Telegram Desktop

4.4.1 x64 and also 4.4.3 beta x64

### Installation source

Static binary from official website

### Logs

```shell
[2022.12.30 17:08:11] MTP Info: -404 error received in 160001 with temporary key, assuming it was destroyed.
[2022.12.30 17:13:35] Update Error: could not get current version 3
[2022.12.30 17:13:35] Update Error: MTP platform 'win64' not found in response.
```

**Comment by ortwinbachmann30** [comment]
why did you do that?

**Comment by 23rd** [comment]
I thought I had fixed this problem.

**Comment by ortwinbachmann30** [comment]
No the problem persists for me!

**Comment by ortwinbachmann30** [comment]
I think the problem fixed. You can close now or keep it open for further checks.
